source :rubygems

gem 'sinatra'
gem 'service_manager'
gem 'activerecord'
gem 'sqlite3'

group :development do
  gem 'rspec'
  gem 'cucumber'
  gem 'capybara'
  gem 'guard'
  gem 'launchy'
  gem 'guard-cucumber'
end
